package com.java.class39_Dec13_ExceptionHandling;

public class ExceptionExample2 {
    public static void main(String[] args) {

//        try {
//            int[] a = {23, 45, 56};
//            System.out.println(a[3]);
//
//            String str = "null";
//            System.out.println(str.length());
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.err("Sorry! Index is out of bound!");
//        } catch (NullPointerException e) {
//            System.out.err("Sorry! You are accessing null Object!");
//        } catch (ArithmeticException e) {
//            System.out.err("Sorry! Something went wrong!");
//        } catch (Exception e) { // this catch has to be at the end only
//            System.out.err("Sorry! Something went wrong!");
//        }
    }
}